name: Build C++ Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Find and build vcxproj
      run: |
        dir /s *.vcxproj
        msbuild /p:Configuration=Release $(for /r %i in (*.vcxproj) do @echo %i)
